server:
  port: 8084
dubbo:
  application:
    name: frontend-search
  registry:
    address: zookeeper://192.168.8.128:2181
    timeout: 50000
  protocol:
    port: 20882
    name: dubbo


#spring:
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.8.138:9300
spring:
  elasticsearch:
    rest:
      uris: http://192.168.8.132:9200
  profiles:
    active: redis