server:
  port: 8081

spring:
  profiles:
    active: itemmapper #,rabbitmq

dubbo:
  application:
    name: backend-item
  registry:
    address: zookeeper://172.16.44.129:2181
    timeout: 50000
  protocol:
    name: dubbo
    port: 20888