server:
  port: 8082

spring:
  profiles:
    active: itemmapper,rabbitmq

dubbo:
  application:
    name: backend-item
  registry:
    address: zookeeper://192.168.8.128:2181
    timeout: 50000
  protocol:
    name: dubbo
    port: 20889