spring:
  mail:
    # 当前网站给别人发送邮件，使用哪个邮件进行发送
    username: jxzyyx_smallming@163.com
    # 不是你邮箱登录密码，是开启pop3/smtp后只显示一次的授权码
    password: RGQUTWZRJFOIJUSW
    # 选择好你的邮箱对应的主机
    host: smtp.163.com
    properties:
      mail:
        smtp:
          # 开启邮箱客户端功能（通俗：能让邮箱通过代码发送邮件）
          auth: true


server:
  port: 9999

dubbo:
  application:
    name: frontend-email
  registry:
    address: zookeeper://192.168.8.128:2181
    timeout: 50000
  protocol:
    port: 20884
    name: dubbo
  provider:
    timeout: 50000
