server:
  port: 8085
dubbo:
  application:
    name: frontend-item
  registry:
    address: zookeeper://192.168.8.128:2181
    timeout: 50000
  protocol:
    port: 20881
    name: dubbo
spring:
  profiles:
    active: itemmapper,redis
