server:
  port: 8088
spring:
  profiles:
    active: ordermapper,redis,rabbitmq


dubbo:
  application:
    name: frontend-trade
  registry:
    address: zookeeper://192.168.8.128:2181
    timeout: 50000
  protocol:
    port: 20889
    name: dubbo