server:
  port: 8086
dubbo:
  application:
    name: frontend-passport
  registry:
    address: zookeeper://192.168.8.128:2181
    timeout: 50000
spring:
  profiles:
    active: redis,usermapper
